//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWEFH45912A.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool JukeboxEnable {
            get {
                return ((bool)(this["JukeboxEnable"]));
            }
            set {
                this["JukeboxEnable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GameLogCleannerEnabled {
            get {
                return ((bool)(this["GameLogCleannerEnabled"]));
            }
            set {
                this["GameLogCleannerEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WebLoginSetting {
            get {
                return ((int)(this["WebLoginSetting"]));
            }
            set {
                this["WebLoginSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ServiceConfig {
            get {
                return ((string)(this["ServiceConfig"]));
            }
            set {
                this["ServiceConfig"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoPlayMusic {
            get {
                return ((bool)(this["AutoPlayMusic"]));
            }
            set {
                this["AutoPlayMusic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1800,1000")]
        public string VideoMode_Size {
            get {
                return ((string)(this["VideoMode_Size"]));
            }
            set {
                this["VideoMode_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int RenderQuality {
            get {
                return ((int)(this["RenderQuality"]));
            }
            set {
                this["RenderQuality"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CustomSettingEnabled {
            get {
                return ((bool)(this["CustomSettingEnabled"]));
            }
            set {
                this["CustomSettingEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MCVoiceTweak {
            get {
                return ((int)(this["MCVoiceTweak"]));
            }
            set {
                this["MCVoiceTweak"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CharVoiceTweak {
            get {
                return ((int)(this["CharVoiceTweak"]));
            }
            set {
                this["CharVoiceTweak"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AFKEnabled {
            get {
                return ((bool)(this["AFKEnabled"]));
            }
            set {
                this["AFKEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LoggingEnabled {
            get {
                return ((bool)(this["LoggingEnabled"]));
            }
            set {
                this["LoggingEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int AFKInterval {
            get {
                return ((int)(this["AFKInterval"]));
            }
            set {
                this["AFKInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CustomTextureTweak {
            get {
                return ((bool)(this["CustomTextureTweak"]));
            }
            set {
                this["CustomTextureTweak"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CustomFontEnabled {
            get {
                return ((bool)(this["CustomFontEnabled"]));
            }
            set {
                this["CustomFontEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MenuPosition {
            get {
                return ((int)(this["MenuPosition"]));
            }
            set {
                this["MenuPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("shutdown -s -f -t 5")]
        public string CommandLineCode {
            get {
                return ((string)(this["CommandLineCode"]));
            }
            set {
                this["CommandLineCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GameDirectory {
            get {
                return ((string)(this["GameDirectory"]));
            }
            set {
                this["GameDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GameUserId {
            get {
                return ((string)(this["GameUserId"]));
            }
            set {
                this["GameUserId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GameUserPassword {
            get {
                return ((string)(this["GameUserPassword"]));
            }
            set {
                this["GameUserPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SteamLauncherMode {
            get {
                return ((bool)(this["SteamLauncherMode"]));
            }
            set {
                this["SteamLauncherMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("default")]
        public string UILanguage {
            get {
                return ((string)(this["UILanguage"]));
            }
            set {
                this["UILanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PatcherWorkingDirectory {
            get {
                return ((string)(this["PatcherWorkingDirectory"]));
            }
            set {
                this["PatcherWorkingDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GameLanguage {
            get {
                return ((string)(this["GameLanguage"]));
            }
            set {
                this["GameLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PatcherLastTab {
            get {
                return ((string)(this["PatcherLastTab"]));
            }
            set {
                this["PatcherLastTab"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PatcherExtCredentials {
            get {
                return ((string)(this["PatcherExtCredentials"]));
            }
            set {
                this["PatcherExtCredentials"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RestoreSettingFromOldAssembly {
            get {
                return ((bool)(this["RestoreSettingFromOldAssembly"]));
            }
            set {
                this["RestoreSettingFromOldAssembly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NewSkipList {
            get {
                return ((string)(this["NewSkipList"]));
            }
            set {
                this["NewSkipList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public string WindowsLocation {
            get {
                return ((string)(this["WindowsLocation"]));
            }
            set {
                this["WindowsLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool KeyboardShortcut {
            get {
                return ((bool)(this["KeyboardShortcut"]));
            }
            set {
                this["KeyboardShortcut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CloseLauncherAlso {
            get {
                return ((bool)(this["CloseLauncherAlso"]));
            }
            set {
                this["CloseLauncherAlso"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CustomInterfaceEnabled {
            get {
                return ((bool)(this["CustomInterfaceEnabled"]));
            }
            set {
                this["CustomInterfaceEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UICustomLaunchOption {
            get {
                return ((string)(this["UICustomLaunchOption"]));
            }
            set {
                this["UICustomLaunchOption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CourtSetting {
            get {
                return ((string)(this["CourtSetting"]));
            }
            set {
                this["CourtSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CameraEnable {
            get {
                return ((bool)(this["CameraEnable"]));
            }
            set {
                this["CameraEnable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CameraSettings {
            get {
                return ((string)(this["CameraSettings"]));
            }
            set {
                this["CameraSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LoadingBgCount {
            get {
                return ((int)(this["LoadingBgCount"]));
            }
            set {
                this["LoadingBgCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"brb	be right back
ttyl	talk to u later
gtg	gotta go
smh	smh my head
rip	RIP in peace
gg	gg noobs ez clap
usuck	If I wanted to commit suicide, I'd jump from your ego to your elo
urmom	Your mom so fat Thanos had to snap twice
eventgkash	Unable to purchase with event Gkash
fs2dev	Our Team will not let this pass nor tolerate this kind of Illegal Activity in-game
violet	Violet from team Arcana I love you. I truly love you, you fill the void in my heart and stop the pain
zeeman	Hi your komputar has virus
takatto	Remember to keep the chats respectful and to follow our Community guidelines
censor	********
uok	You haven't violated any community standards in last few weeks, are you ok?
oggway	Yesterday is history, Tomorrow is a mystery, but today is a gift. That is why it is called the present.
mtherfker Your mother is what we called a shared resource
s3x	Add sex to fs2 :pray:
uwu	Don't you fucking uwus on me")]
        public string TextMacroData {
            get {
                return ((string)(this["TextMacroData"]));
            }
            set {
                this["TextMacroData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TextMacroEnable {
            get {
                return ((bool)(this["TextMacroEnable"]));
            }
            set {
                this["TextMacroEnable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CustomPatchRepository {
            get {
                return ((string)(this["CustomPatchRepository"]));
            }
            set {
                this["CustomPatchRepository"] = value;
            }
        }
    }
}
